server:
  port: 8085   # Notification Service runs on its own port

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: mopuruniranjan070@gmail.com
    password: Niranjan070@   # use an app password, not your real Gmail password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
